# Generated by Django 4.2.1 on 2023-05-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('New', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Автор'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='autorRating',
            new_name='ratingAutor',
        ),
    ]
